### ISSUE TITLE
Example : how to use mbus.js 

### ISSUE THREAD

**Issue by DruhBoruch** [ganehag/mbusJS#1]
Hi 

Could you pleas provide a brief example of how to use mbus.js to read data from serial port ?

**Comment by ganehag** [comment]
Absolutely. I will throw something together later today.

**Comment by ganehag** [comment]
I've written a small application and added it to the examples folder. I moved all of the *.blob frames from the examples folder into their own "frames" folder. The app "serial-read.js" uses nodejs:s serialport to work.

**Comment by DruhBoruch** [comment]
Thank you very much for this piece of code, it will save me a lot of work

**Comment by ganehag** [comment]
Hope it works for you. Can't promise anything...
